### ISSUE TITLE
Add keyboard functions for camera movement

### ISSUE THREAD

**Issue by petevieira** [golems/grip2#26]

**Comment by joosm** [comment]
Keyboard bindings for camera manipulation:
- zoom in/out: +/- key
- camera moves to the left/right: left/right arrow key
- camera move up/down: up/down arrow key
- camera rotate left/right: H/L key
- camera rotate up/down: J/K key

**Comment by petevieira** [comment]
Hey Sungmoon,

That's great!

I think what we said we wanted was keys that you hold while using the left
click on the mouse to operate the camera.
This would therefore only require three different keys, Control, Shift and
Alt in order to Rotate, Pan and Zoom respectively, as these are fairly
standard among 3D programs I believe.

Let me know you're thoughts.

Thanks,

Pete

On Tue, Apr 22, 2014 at 3:57 PM, joosm notifications@github.com wrote:

> Keyboard bindings for camera manipulation:
> - zoom in/out: +/- key
> - camera moves to the left/right: left/right arrow key
> - camera move up/down: up/down arrow key
> - camera rotate left/right: H/L key
> - camera rotate up/down: J/K key
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/golems/grip2/issues/26#issuecomment-41087909
> .

## 

## 

Peter Vieira
Masters Student
Electrical & Computer Engineering
Center for Robotics & Intelligent Machines
Georgia Institute of Technology
Pete.Vieira@gmail.com
_"I'm gonna be a ramblin' wreck from_
_Georgia Tech and a hell of an engineer"_

**Comment by joosm** [comment]
Added keyboard+mouse bindings for camera manipulation
- Zoom in/out: Left Ctrl key + Mouse(Keypad) move up/down
- Camera move left/right/up/down: Left Shift key + Mouse move left/right/forward/backward
- Camera Rotation: Left Alt key + Mouse move
