### ISSUE TITLE
cmake inconsistency

### ISSUE THREAD

**Issue by mxgrey** [golems/grip2#33]
Line 49 of the root CMakeLists.txt uses EIGEN_INCLUDE_DIRS after invoking find_package on the file cmake/FindEigen.cmake. But cmake/FindEigen.cmake sets a variable Eigen_INCLUDE_DIRS, not EIGEN_INCLUDE_DIRS. Also it never sets anything called EIGEN_DEFINITIONS, so using it in add_definitions would do nothing.

I think if you print out EIGEN_INCLUDE_DIRS using

message(STATUS "${EIGEN_INCLUDE_DIRS}")

it will probably show up blank, unless it secretly gets set somewhere else. So we should either use

include_directories(${Eigen_INCLUDE_DIRS})

or we should leave it out entirely.

**Comment by petevieira** [comment]
Fixed by just using Eigen_INCLUDE_DIR and removing the EIGEN_DEFINITIONS
